# permissions for end users to view tanzunamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzunamespace-viewer-role
rules:
- apiGroups:
  - tenancy.platform.cnr.vmware.com
  resources:
  - tanzunamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenancy.platform.cnr.vmware.com
  resources:
  - tanzunamespaces/status
  verbs:
  - get
