# permissions for end users to edit tanzunamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzunamespace-editor-role
rules:
- apiGroups:
  - tenancy.platform.cnr.vmware.com
  resources:
  - tanzunamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenancy.platform.cnr.vmware.com
  resources:
  - tanzunamespaces/status
  verbs:
  - get
