---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: namespace-operator
  namespace: default
  name: namespace-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namespace-operator
  template:
    metadata:
      labels:
        app: namespace-operator
      name: namespace-operator
    spec:
      serviceAccountName: namespace-operator-admin
      containers:
        - name: namespace-operator
          image: projects.registry.vmware.com/cnr_project_ivy/namespace-operator:v1.2.7
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
