---
name: Test
on:
  - push
  - pull_request
jobs:
  Go Lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  Docker Lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hadolint
        uses: brpaz/hadolint-action@v1.2.1

  Go Test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Install KubeBuilder
        uses: RyanSiu1995/kubebuilder-action@v1.1
      - name: go test
        run: make test
